### ISSUE TITLE
Class 'WYSIWYG' not found

### ISSUE THREAD

**Issue by Malezha** [LaravelRUS/SleepingOwlAdminDemo#1]
[Страница с демо контактами третей версии](http://sleepingowl.kodicms.ru/admin/contacts3) падает с исключением
```
FatalErrorException in Wysiwyg.php line 39:
Class 'WYSIWYG' not found
```

**Comment by butschster** [comment]
Да, я знаю об этой проблеме, проблема решится когда реализую работу с wysiwyg редакторами
