### ISSUE TITLE
Class KodiCMS\Users\Model\User does not exist

### ISSUE THREAD

**Issue by Malezha** [LaravelRUS/SleepingOwlAdminDemo#2]
[Страница со списком пользователей](http://sleepingowl.kodicms.ru/admin/users) вылетает с исключением
```
Class KodiCMS\Users\Model\User does not exist
```

**Comment by butschster** [comment]
Скорее всего придется отключить этот раздел, потому что, этот класс был первый, на котором я тестировал возможности и оставил как пример.

**Comment by butschster** [comment]
Класс удален
